attempt to add sponsor logos to footer
be-oi/beoi-contest-platform pull request #11
Opened 2017-01-21 15:19 UTC by jganseman

Needs review and local testing!

- sponsor logos added in images dir for contestInterface and teacherInterface
- divFooter expanded (similar to divHeader).
- now hardcoded links. Once tested inline and style is OK, needs to be moved to translation.json like beoi logos for easy future replacement.

2017-01-21 18:18 UTC, smadbe commented
shouldn't we be sure they sign first ?

2017-01-21 19:56 UTC, jganseman commented
Sure, it's only meant to be merged when contract is finalized. But could maybe already be reviewed as I coded this blindly without setting up a PHP server


Op 21 jan. 2017 7:18 p.m. schreef Damien Leroy <notifications@github.com>:

shouldn't we be sure they sign first ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/be-oi/beoi-contest-platform/pull/11#issuecomment-274278487>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AAh5UROUqsYd0yU2XFeSxVd1mo0adUVpks5rUkvzgaJpZM4LqGAa>.

2017-01-23 21:38 UTC, smadbe requested changes

2017-01-23 21:38 UTC, smadbe commented on teacherInterface/index.php
> +
not ok, floating on top and hiding instructions

2017-01-23 21:38 UTC, smadbe commented on contestInterface/index.php
>  </div>
Not displayed. 

But anyway, should not be displayed in the actual contest interface, I'm afraid it interferes in some browsers/config.

2017-01-28 17:24 UTC, smadbe commented
done in other branches

2017-01-28 17:24 UTC, closed without merging